pref("browser.startup.homepage",        "chrome://cck-guada/content/cck.properties");
pref("startup.homepage_override_url",   "");
pref("startup.homepage_welcome_url",   "");
pref("browser.search.defaultenginename", "chrome://cck-guada/content/cck.properties");
pref("browser.search.order.1",           "chrome://cck-guada/content/cck.properties");
pref("network.proxy.type", 0);
pref("network.protocol-handler.app.apt","/usr/bin/apturl");
pref("network.protocol-handler.warn-external.apt",false);
pref("network.protocol-handler.app.apt+http","/usr/bin/apturl");
pref("network.protocol-handler.warn-external.apt+http",false);
pref("network.protocol-handler.external.apt",true);
pref("network.protocol-handler.external.apt+http",true);
